M48
; DRILL file {KiCad 9.0.2} date 2025-05-15T00:42:00-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-15T00:42:00-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X72.5Y-121.0
X72.5Y-125.6
T2
X36.5Y-24.0
X39.5Y-160.5
X190.0Y-26.5
X191.5Y-157.0
M30
